version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - JamesMura
  ignore:
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: gulp-filter
    versions:
    - 6.0.0
